model:
    type: 'CGNet'
    backbone:
        m: 3
        n: 21
        classes: 19
        dropOutFlag: False
        pretrained: "weights/model_cityscapes_train_on_trainvalset.pdparams"


data:
    set:
        train:
            root: "data/Cityscapes"
            list_path: "data/list/Cityscapes/cityscapes_train_list.txt"
            crop_size: (512, 1024)
            scale: True,
            mirror: True

        val:
            root: "data/Cityscapes"
            list_path: "data/list/Cityscapes/cityscapes_val_list.txt"

        trainva:
            root: "data/Cityscapes"
            list_path: "data/list/Cityscapes/cityscapes_trainval_list.txt"
            crop_size: (512, 1024)
            scale: True
            mirror: True

    loader:
        train:
            batch_size: 16
            shuffle: True
            num_workers: 1
            use_shared_memory: True
            drop_last: True

        val:
            batch_size: 1
            shuffle: False
            num_workers: 0
            use_shared_memory: True
            drop_last: False

train:
    max_epochs: 360
    opt:
        learning_rate: 0.001
        max_epoch: 360
        last_epoch: -1
        verbose: False

    resume:
        last_epoch: -1
        lr: 0.001
